name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cat /etc/*release
        grep MH /proc/cpuinfo
        free -h
        curl -s https://inet-ip.info/ip
        dig jsx.jp
        dig proxy.secure.jsx.jp
        dig gcp.jsx.jp
        dig aws.jsx.jp
        npm i
        npm run build --if-present
        npm test
      env:
        CI: true
